### ISSUE TITLE
A questions about this paper

### ISSUE THREAD

**Issue by robinxlh** [sunjss/CoCN#1]
Hello, I would like to inquire about why in Eq. A.11, 1P = 1?

**Comment by sunjss** [comment]
Hi! This is in accordance with the definition of a permutation matrix, where the entries are either 0 or 1, and the sum of each row and each column equals 1.

**Comment by robinxlh** [comment]
Thank you, I get it. But I still have some confusion.
I noticed that your work seems to not utilize message passing for updating node features, except for the use of the Laplacian operator in generating relative node positions. It appears that in the CoCNModuleN class, you take a continuous subset of node features from the feature matrix X, and then directly concatenate them with the corresponding local adjacency matrix features, followed by a linear mapping. I tentatively understand this as a form of subgraph convolution, although my understanding may not be entirely accurate.

Here are my specific concerns:

Firstly, I don't quite grasp the purpose of the permutation matrix P (perm) and it seems that it does not ensure a fixed order of node features X after transformation. This could result in different consecutive (filter_size) nodes being selected for the feature matrix X under a different node ordering within the same graph. I'm concerned that this might make the network fail to achieve permutation invariance.

Secondly, I find it difficult to understand why this novel node-ordered convolution surpasses traditional message passing methods.

I would greatly appreciate it if you could address these concerns and clarify my doubts.

**Comment by sunjss** [comment]
Yes, the CoCNModuleN incorporates a hierarchical subgraph convolution. 

In the permutation module, we introduce randomness to distinguish nodes with identical positional assignments. Since the reordering of overlapping nodes is generated randomly, it remains statistically invariant to the input order. Furthermore, we have found that this component can potentially be omitted with certain refinements, which we are actively investigating in ongoing experiments.

Regarding your second concern, the compressed convolution separates the message-passing pathway from the input structure and facilitates explicit hierarchical feature learning for both node and edge features. For a more in-depth analysis, please refer to our paper.

We genuinely appreciate your interest in our work 😊.

**Comment by robinxlh** [comment]
Thank you once again for your patient response. After reviewing the PermGenModule class in the code, I think I understand why the node feature ordering  becomes fixed when the relaxation factor τ approaches infinity. It's truly a novel approach to permutation generation.
By the way, I think  incorporating random biases to nodes serves as a means to prevent nodes with similar local structures and features from sharing the same positional order, which can be viewed as a  special  node augmentation strategy. If you desire completely distinct node features within a graph, perhaps you can try incorporating LapPE for each node. 
In the end, I have to say that it is a excellent work  and I learn a lot.

**Comment by sunjss** [comment]
Thank you for your recognition and support. LapPE is a great idea, and we'll definitely give it a try.
